### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lucaspolizeli** [lucaspolizeli/centauro-challenge#1]
# Requisitos :rocket: 
- [x] Buscar por um usuário no GitHub, e ver os repositórios mais populares. 
- [x] Ver os detalhes do usuário selecionado. (número de seguidores, número de seguidos, avatar, e-mail, e bio).
- [x] Ordenar repositórios por stars, decrescente, ou crescente (default é decrescente).
- [x] Ver em uma página detalhada de cada repositório (nome, descrição, nº de estrelas, linguagem principal e link para o repositório).

# Requisitos Técnicos :robot: 
- [x] Responsividade 
- [x] User Rotas
- [x] Usar Store
- [x] Testes (Jest)

# Extras :exclamation: 
- [x] Styled-Components
- [x] Documentação.
- [x] Layout Bonito
- [x] Hospedar aplicação (Circle CI + Heroku).
